[theme]
base = "light"
primaryColor = "#CC4628"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#1a1a1a"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
