[theme]
# Mines branding - Light theme
primaryColor = "#CC4628"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#CFDCE9"
textColor = "#21314d"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
